name: Update README

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows 
    name: Update this repo's README with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: yahyadhaou/github-activity-readme@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
